add parted check

diff --git a/files/n1-install b/files/n1-install
--- a/files/n1-install
+++ b/files/n1-install
@@ -1,23 +1,17 @@
 #!/bin/sh
 
-error() {
-    echo -e "\033[31m Error:\033[0m $1"
+die() {
+    echo -e "\033[31m Error:\033[0m $1" && exit 1
 }
 
 emmc=$(lsblk | grep -oE 'mmcblk[0-9]' | sort | uniq)
 sd=$(lsblk | grep -oE 'sd[a-z]' | sort | uniq)
 
-[ $emmc ] || {
-    error "no emmc found!" && exit 1
-}
-[ $sd ] || {
-    error "no usb device found!" && exit 1
-}
+[ "$emmc" ] || die "no emmc found!!"
+[ "$sd" ] || die "no usb device found!!"
 
 sd=$(lsblk | grep -w -E '/|/overlay' | grep -oE 'sd[a-z]')
-[ $sd ] || {
-    error "you are running in emmc mode, please boot system with usb!" && exit 1
-}
+[ "$sd" ] || die "you are running in emmc mode, please boot system with usb!!"
 
 dev_emmc="/dev/$emmc"
 dev_sd="/dev/$sd"
@@ -29,7 +23,7 @@ if (blkid -L "BOOT_EMMC" && blkid -L "ROOT_EMMC") >/dev/null 2>&1; then
     installed=true
 fi
 
-if (grep -q $dev_emmc /proc/mounts); then
+if grep -q $dev_emmc /proc/mounts; then
     echo " umount emmc..."
     umount -f ${dev_emmc}p* >/dev/null 2>&1
 fi
@@ -38,6 +32,8 @@ part_boot="${dev_emmc}p1"
 part_root="${dev_emmc}p2"
 
 if [ ! $installed ]; then
+    parted -v >/dev/null 2>&1 || die "package parted not found!!"
+
     echo " backup u-boot..."
     dd if=$dev_emmc of=u-boot.img bs=1M count=4
 
@@ -52,7 +48,7 @@ if [ ! $installed ]; then
 
     sync
 
-    if (grep -q $dev_emmc /proc/mounts); then
+    if grep -q $dev_emmc /proc/mounts; then
         echo " umount emmc..."
         umount -f ${dev_emmc}p* >/dev/null 2>&1
     fi
@@ -119,7 +115,7 @@ tar -cf - usr | (cd $ins_root && tar -xpf -)
 echo "  --> copy www..."
 tar -cf - www | (cd $ins_root && tar -xpf -)
 
-[ -f init ] && cp -a init $ins_root
+[ -f init ] && cp -f init $ins_root
 
 cd $ins_root
 mkdir boot dev mnt opt overlay proc rom run sys tmp
